- hosts: localhost
  connection: local
  tasks:
    - name: install python2-pip, git
      yum: pkg={{ item }} state=installed enablerepo=epel
      with_items:
        - python2-pip
        - git
        - gcc
        - gcc-c++
        - make
        - openssl-devel
        - bzip2-devel
        - zlib-devel
        - readline-devel
        - sqlite-devel
        - libffi-devel
      become: yes
    - block:
      - name: install pipenv
        pip:
            name: pipenv
            extra_args: --user
      - name: git clone pyenv
        git:
          repo=git://github.com/yyuu/pyenv.git
          dest=~/.pyenv
      - name: git clone pyenv virtualenv plugin
        git:
          repo=git://github.com/yyuu/pyenv-virtualenv.git
          dest=~/.pyenv/plugins/pyenv-virtualenv
      when: not ansible_check_mode
    - name: add pyenv setting
      blockinfile:
        path: ~/.bash_profile
        block: |

          ## pyenv/pipenv
          if [ -d ${HOME}/.pyenv ]; then
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            eval "$(pipenv --completion)"
            export PIPENV_VENV_IN_PROJECT=1
          fi
    - name: pyenv install python 3.6.6
      shell: source ~/.bash_profile && pyenv install 3.6.6
      changed_when: False
      register: pyenv_installed
      failed_when: pyenv_installed.rc not in [0, 1]
